### ISSUE TITLE
How should we do Arabic-English alignment for new texts from LHOM edition/translation?

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#10]
The new texts use numbered, nested divs: See https://github.com/usaybia/usaybia-data/blob/master/data/texts/tei/lhom/lhom-ar-01.xml#L109 (my reworked file) or https://dh.brill.com/scholarlyeditions/library/passage/urn:cts:arabicLit:0668IbnAbiUsaibia.Tabaqatalatibba.lhom-tr-eng1:1.1-1.5/xml/ line 4ff. for the English equivalent. 

Arabic:
```
<div type="edition" n="urn:cts:arabicLit:0668IbnAbiUsaibia.Tabaqatalatibba.lhom-ed-ara1" xml:lang="ar-Arab">
                <div type="textpart" subtype="chapter" n="1">
                    <div type="textpart" subtype="biography" n="1">
```

English:
```
<div type="translation" n="urn:cts:arabicLit:0668IbnAbiUsaibia.Tabaqatalatibba.lhom-tr-eng1" xml:lang="en-Latn">
<div type="textpart" subtype="chapter" n="1">
<div type="textpart" subtype="biography" n="1">
```

How does this work with the parallel text display module you already implemented? (See #1)

**Comment by nathangibson** [comment]
Related? #7

**Comment by nathangibson** [comment]
@wsalesky Fortunately (and unfortunately) we have access to a great new Arabic edition and English translation of the text. I'm considering putting the Arabic and English of each chapter into a single TEI file, aligned paragraph by paragraph, since they're structured very similarly. 

```
<div type="edition"
              n="urn:cts:arabicLit:0668IbnAbiUsaibia.Tabaqatalatibba.lhom-ed-ara1">
    <div type="textpart" subtype="chapter" n="14">
        <div type="textpart"
            subtype="biography"
            n="1">
            <head xml:lang="ar">
                    الباب الرابع عشر في طبقات الأطباء المشهورين من أطباء ديار مصر
                    <note n="1" xml:lang="en" type="footnote" anchored="true">
                        <p>...</p>
                    </note>
                    ‬‎
                </head>
            <head xml:lang="en">
                    Chapter 14 Famous Physicians amongst Those in Egypt
                    <note n="1" type="footnote">
                        <p>...</p>
                    </note>
                </head>
            <head xml:lang="en">Franak Hilloowala, Emilie Savage-Smith and Geert Jan van Gelder (poetry)</head>
            <div type="textpart"
            subtype="biography-part"
            n="1">
                <p xml:lang="ar">
                    <hi rend="bold">
                        ‭[14.1]‬ بليطيان <note n="2" xml:lang="en" type="footnote" anchored="true">
                            <p>The first biography is missing from Version 1, but is found in Versions 2 and 3. It is written in the margin of R.</p>
                        </note>
                    </hi>
                </p>
                <p xml:lang="en">
                        <hi rend="bold">
                            14.1 Politianus (Balīṭīyān)
                            <note n="2" type="footnote">
                                <p>...</p>
                            </note>
                        </hi>
                </p>
                <p xml:lang="ar">بليطيان كان طبيباً مشهوراً بديار مصر نصرانياً عالماً بشريعة النصارى الملكية.‬‎</p>
                <p xml:lang="en">Politianus (Balīṭīyān) was a famous physician in Egypt and a Christian scholar of the Melkite sect.</p>
            </div>
        </div>
    </div>
</div>
```

Here are the main points regarding alignment and display: 
- each HTML page should 1 lowest-level div (e.g., biography-part here, whatever level doesn't contain more divs), plus all heads from ancestor divs.
- `@xml:lang` is used to indicate Arabic/English - Arabic should go in the right column, English in the left
- progression (page sequencing) is from one lowest-level div to the next lowest-level div
- we will need to be able to resolve references to passages, possibly in the form of CTS URNs, e.g. here urn:cts:arabicLit:0668IbnAbiUsaibia.Tabaqatalatibba.lhom-ed-ara1:14.1.1 = `//div[@n="urn:cts:arabicLit:0668IbnAbiUsaibia.Tabaqatalatibba.lhom-ed-ara1"]/div[@n="14"]/div[@n="1"]/div[@n="1"]`

What do you think of this conceptually and functionally? How easy would it be to adapt the text display you worked up earlier to do this? Practically speaking, it means there would be no real alignment necessary, just sequencing divs.

**Comment by wsalesky** [comment]
@nathangibson I think this is a reasonable approach. I should be able to easily adapt the existing code to use the code for this. Let me know when you have an English and Arabic example and I will work up a test for the development branch

**Comment by nathangibson** [comment]
Excellent, thanks!
