### ISSUE TITLE
Experimental network visualizations

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#104]
@wsalesky I have some ideas for some other D3JS visualizations, besides the force directed graphs. But I don't want to ask you to put a lot of work into incorporating them into the app if I'm not sure they'll be useful. 

If I were to experiment in some "notebooks" at Observable HQ (e.g., https://observablehq.com/@d3/arc-diagram) would that make it easy for you to copy the D3JS code into the app and make tweaks once I've decided on the ones I want to go for?

**Comment by wsalesky** [comment]
@nathangibson  Sure, that would be a great.
