### ISSUE TITLE
Customize person detail display

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#13]
Waiting on #12

**Comment by nathangibson** [comment]
@wsalesky You now have a whole bunch of very basic person records to play with: https://github.com/usaybia/usaybia-data/tree/master/data/persons/tei 

Can you try those out in a local install?

**Comment by wsalesky** [comment]
@nathangibson Thanks, I will spin up a local instance, hopefully this weekend and will let you know how it looks.

**Comment by nathangibson** [comment]
Working on getting a server running (#21), any updates in the meantime?

**Comment by wsalesky** [comment]
@nathangibson So sorry! I have been swamped. I will try to get something up this week.

**Comment by nathangibson** [comment]
Thanks! I understand!

**Comment by wsalesky** [comment]
@nathangibson Can this be closed?

**Comment by nathangibson** [comment]
Yes, we might reopen it at some point when we have more tweaks
