### ISSUE TITLE
Experiment with advanced network visualization

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#15]
You'll need more data from me but for new check out the D3JS behind  http://www.sixdegreesoffrancisbacon.com and see if there's anything useful to implement from there

**Comment by wsalesky** [comment]
@nathangibson Is there relationship data in the persons data? Are you following Syriaca.org TEI relationships? Something else?

**Comment by nathangibson** [comment]
So this is something I wanted to discuss with you. There will be different networks coming from different sources. 
 1. Network from TEI relation factoids (like SPEAR)
 2. Network(s) (currently in spreadsheets), destination format TBD 

Should we put no. 2 into factoid format, so that you don't have to build different queries for it? Or perhaps just a list of TEI relations, but not in factoid divs? Or RDF? 

Let me know what you'd like as samples.

**Comment by wsalesky** [comment]
@nathangibson A list of relations is fine to start us off.

**Comment by wsalesky** [comment]
@nathangibson Checking in on this issue, is there data for me to experiment with?

**Comment by nathangibson** [comment]
Hi @wsalesky (finally!)
Please see the commit referenced just above :-)

**Comment by nathangibson** [comment]
That is a relatively small network, using real URIs and (mostly) valid TEI, but the refs on the relations are preliminary and not URIs.

**Comment by nathangibson** [comment]
And here is a huge network (40,000+ relations), where the relations are mutual and the refs indicate the reference for the passages the two persons in each relation co-occur in.

**Comment by nathangibson** [comment]
You're welcome to do your testing on the dev branch if you like. 
Edit: I mean on the dev server.

**Comment by wsalesky** [comment]
@nathangibson FYI Getting started on these this week.

**Comment by wsalesky** [comment]
@nathangibson What kind of functionality are you looking to explore with these visualizations? Thinking in terms of how you want to be able to interrogate the relationships. For example: do you want to filter by person occupation, relationship type, limit to a single person or place, search within a graph? Something else? 
I have a basic network graph working, but it is not very useful without more data/functionality. 
Example (index-relations.xml): 
<img width="970" alt="Screen Shot 2020-11-20 at 2 04 04 PM" src="https://user-images.githubusercontent.com/1168206/99839772-483cb380-2b39-11eb-9964-6e10416eb3f5.png">

**Comment by nathangibson** [comment]
@wsalesky Thanks, looks like a great start! 

Yes, there will be a number of things to refine both in the data and in the display. 

1. Some will be analogous to "facets" in the advanced browse, but we don't have all the data there for that yet. Being able to filter by occupation would be a good start. See e.g. https://usaybia.net/persons/browse.html?facet-occupation=physician&view=facets. I would envision this as a "matches criteria" vs. "doesn't match criteria" color difference for the nodes. Six Degrees of Francis Bacon does this well, e.g. with "judges" http://www.sixdegreesoffrancisbacon.com/?ids=124&min_confidence=60&type=network I believe they're using d3js and that there code is open source (on Github?) 
2. I would also like to be able to distinguish relationship types in a similar way using edge colors, perhaps also just "matches criteria" vs. "doesn't match criteria".
3. I would like to be able to show the network of a selected/searched individual, probably to the 2nd degree.

There are other things that might require implementing a network analysis library (networkx for python?) if we want to do them live, such as adjusting size to reflect betweenness centrality and finding shortest paths between two individuals. Or alternatively we pre-analyze these and include them in the data, displaying them only when they are applicable to the current view. Just something to keep in the back of our brains.

**Comment by nathangibson** [comment]
@wsalesky I'm going to break this into more specific sub-issues -- hope that will be easier to track.
