### ISSUE TITLE
Basic Rebranding

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#2]
Are you interested in using your visual design skills too? Was wondering if you would want to go through and rebrand the Srophe app (at this point at a basic level). 

There is a placeholder page here: https://usaybia.net so you can see some the project title and some copy text/images. I've invited you to the repo that runs it. It's built on Bootstrap, so should be easy to copy-paste any styles you want to keep. I like the general look of it but I'm not deeply committed to it. Colors are inspired by my university colors but again not set in stone.

I probably won't plan to use the slider style that Syriaca does for its modules, since the project is supposed to be more of a coherent dataset rather than individual modules. But otherwise I'm open to keeping many of the design elements of the current Srophe, at least initially. 

I don't have a logo yet. The "usaybia.net" address should be prominent but the project title should also be fairly visible. 

This could be an opportunity for further abstraction of the Srophe app.

Questions?

**Comment by wsalesky** [comment]
@nathangibson I think you did a great job with the design on placeholder page. I will see how it goes integrating it into Srophe app. Should not be difficult. Let me know if you want any help with a logo design.

**Comment by nathangibson** [comment]
Thanks :-). Looking forward to it. I built the placeholder with Bootstrap, thinking that could make it easier to use pieces of it in the Srophe app as needed. 

I have a lead on logo design, but if that doesn’t pan out I’ll be glad for the help on that too. Most likely the logo will use the fonts and colors from the placeholder.

**Comment by wsalesky** [comment]
@nathangibson How much of the Syriaca.org infrastructure do you think you will be using? (persons,geo,manuscripts,bibl, saints etc)

**Comment by wsalesky** [comment]
@nathangibson initial changes are up. I do not like how busy the navbar is and would like to either consolidate some of the drop downs, or eliminate them if you are not using them.  I'm not going to do much work on internal pages until I know how much of the app you will be using.

**Comment by nathangibson** [comment]
Wow, that was fast, thanks! 

 - Regarding modules, I don't think we need any of the module landing pages (such as http://syriaca.org/persons/). I expect to have the following entities: persons, places, manuscripts, bibls, and factoids. So we will need the faceted browse, advanced search, and item detail pages for these. But these will not be presented to the user as "volumes" or "modules." (Of course it is fine to keep the modular structure in the code, it just won't be user-facing.) 
- As far as decluttering the navbar: 
  - We don't need the Font dropdown as I won't be using much Syriac on the site. 
  - The advanced search could just be a gear instead of a dropdown, as you had in a previous version of Srophe. 
  - Also, could we reorder the keyboard options so that English and Arabic come first, then Syriac after that. 
  - We can remove "Home" since I think it's pretty standard to click on the website name in the top-left for that (unless you think otherwise). 
- A few images that are on the placeholder page are missing under Objectives and Research Questions.
- Can we add a large search bar underneath the header image? 

Thanks so much.

**Comment by nathangibson** [comment]
Oh, and there won't be any distinction between authors and saints. People will just be people. :-)

**Comment by wsalesky** [comment]
@nathangibson how does it look now?

**Comment by nathangibson** [comment]
Thanks. I like the cleaner navbar. Not totally sure whether I like the position of the search bar, but let's leave it there for now and let me get used to it. Unless you have some other idea for where it should go. Is the thought that it would stay there for all pages across the entire site? 
Still missing some images.

**Comment by wsalesky** [comment]
Another option for the search bar is one that expands when you click the search icon. See this: https://bootsnipp.com/snippets/PjQN9

Then you could pop it back into the top menu.

**Comment by nathangibson** [comment]
Oooh, I like that. Where would the keyboard and advanced search go? Inside the popout? That would be a good option for the top menu, as you say. 

My philosophy is that the landing page should immediately draw the user into engaging with the data. Of course, we don't have data yet to speak of! But in that spirit, I would like the search bar on the home page to be obvious and inviting. So we could have the popout search icon in the top menu, but also have the prominent search bar on the home page (only), perhaps under the header image? What do you think?

**Comment by wsalesky** [comment]
How about this: http://141.40.254.7:8080/exist/apps/usaybia/index.html

I still need to figure out how to get the keyboard menu to show when the search expands, but I think it looks nice.

**Comment by nathangibson** [comment]
Ahh, I like this! Looking more and more refined. I see you were also able to use better mobile-responsive classes on the images than I had originally. 

One slight problem with the popout search—it doesn’t work on a narrow window with the menu collapsed to a hamburger.

**Comment by wsalesky** [comment]
The popout search has a few issues. I can resolve them if you want to keep this look, just didn't want to sink to much time into something we don't use.

**Comment by nathangibson** [comment]
@wsalesky Waiting on #8 unless you want to do more on this locally

**Comment by nathangibson** [comment]
@wsalesky Will close this too based on your preliminary work and make a different issue for extended branding.
