### ISSUE TITLE
Adjust repo-config.xml settings to give the correct link base

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#27]
The app keeps wanting to add usaybia/ or usaybia/persons/ or usaybia/person/ to various paths, most or all of which use $nav-base. I don't think this has to do with nginx because it's the same whether I'm using the server name or IP address + port. 

E.g. if I search for "Ibn" from the home page I get 

> 404 Document /db/apps/usaybia/usaybia/search.html not found
(notice the doubled "usaybia")

If I try to click on a person from the persons/browse.html page I get 

> 404 Document /db/apps/usaybia/persons/usaybia/person/usaybia/persons/usaybia/person/1/index.html not found

I assume this has to do with the various paths in the repo-config.xml but I've tried a couple things with no success.

**Comment by wsalesky** [comment]
@nathangibson This is fixed. Honestly I don't know what was going on. I just rest triggered the webhook for the existing version of the repo-config file. Let me know if you continue to have issues.

**Comment by nathangibson** [comment]
Thanks, but ya this is still giving me some problems. It looks like now accessing it from the IP address + port is behaving correctly, but I'm having trouble when I try to use the server name, like servername.com/usaybia . It keeps trying to add /exist/apps to the address such as if I'm browsing persons at /usaybia/persons/browse.html and click on one it tries to send me to /exist/apps/usaybia/person/2413

Also search and advanced browse give 0 results when using the server name, e.g., /usaybia/search.html?keyword=Ibn or try clicking on Advanced Browse /usaybia/persons/browse.html?view=facets

I imagine the nav-base has to be set differently for these two different scenarios -- IP address with the full /exist/apps/usaybia vs servername.com/usaybia ? If that's the case, then I'd prefer the latter to work since I think that's more similar to what we'll set up when we migrate the usaybia.net domain over.

**Comment by nathangibson** [comment]
Weird, I just uploaded a new batch of data without changing any config files and now neither search nor advanced browse work on either way of accessing the site. Both give 0 results at /exist/apps/usaybia/search.html?keyword=Ibn and /usaybia/search.html?keyword=Ibn respectively.

**Comment by wsalesky** [comment]
@nathangibson Okay, you can sadly not have it both ways, unless you mange the urls outside of eXist. So I have set the root as '/usaybia' this works for the second case you stated: servername.com/usaybia but will not work for the first case.  The other option would be to set the nav-base to '/exist/apps/usaybia' and use nginx to set '/exist/apps/usaybia' as the root.

**Comment by nathangibson** [comment]
Thanks, this is working perfectly now!
