### ISSUE TITLE
Upload bibliography records and test

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#29]
I've managed to generate some bibliography records here https://github.com/usaybia/usaybia-data/tree/master/data/bibl/tei, which are cited by the person records. I tried it locally and it works well. But the webhook isn't working for that update and I've run out of time to upload it manually. 

If you have a chance can you upload to the server please and just make sure the citation is displaying in a roughly readable way on the person records? We don't need to worry about bibliography browsing or filtering at this point.

**Comment by wsalesky** [comment]
@nathangibson I added these. The links do not work in the bibl browse, but they citation does show up in the persons records.

**Comment by nathangibson** [comment]
@wsalesky Thanks!!
