### ISSUE TITLE
Search bar sometimes obliterated by text

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#33]
Some text elements and images obliterate the search bar, i.e., show on top of it rather than underneath. Includes some of the text on the home page and the headword/title on person detail pages. Maybe has to do with z-index? 

See screenshots. 

<img width="646" alt="Screen Shot 2020-06-26 at 1 42 31 PM" src="https://user-images.githubusercontent.com/3083452/85853587-10f8ef00-b7b3-11ea-8d94-64d51ac87dd5.png">

<img width="1121" alt="Screen Shot 2020-06-26 at 1 43 08 PM" src="https://user-images.githubusercontent.com/3083452/85853592-135b4900-b7b3-11ea-9a0c-2a5f08825128.png">

**Comment by wsalesky** [comment]
Z-index and padding on the entry container. Also I think the opacity on the search bar may be a contributing factor. Will investigate.

**Comment by wsalesky** [comment]
Fixed on development branch. Will push to server when webhooks are running.
