### ISSUE TITLE
Change "Usaybia.net Application" in navbar to Usaybia.net

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#34]
Not an important issue but I'm trying to change the "Usaybia.net Application" in the navbar to "Usaybia.net". Have looked in various config places but can't seem to figure out where the "Application" part is coming from.

**Comment by wsalesky** [comment]
I it is coming from here: https://github.com/usaybia/srophe-eXist-app/blob/master/expath-pkg.xml

**Comment by wsalesky** [comment]
@nathangibson I fixed this on dev.
