### ISSUE TITLE
Header name disappears in advanced browse list

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#35]
See screenshot. 

Is this to do with deprecation of `@srophe-tags`? If so, I can change the data. 

![Screenshot_2020-07-07 Usaybia net](https://user-images.githubusercontent.com/3083452/86800603-7e3e3700-c073-11ea-8a95-5449188269dd.png)

**Comment by wsalesky** [comment]
@nathangibson it should display both versions of the headword, but it would be a good idea to change the data.

**Comment by wsalesky** [comment]
@nathangibson fixed on development branch. Will load once webhooks are working again.
