### ISSUE TITLE
Tweak entry citations

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#36]
I'd like to tweak the appearance of the citations and also fix some things that aren't working correctly. 

Currently https://dev.usaybia.net/person/1 shows 

> Nathan P. Gibson et al., “ʿAbbād ibn ʿAbbās” in last modified 2020, https://usaybia.net/person/1.
> Bibliography:
> Nathan P. Gibson et al., “ʿAbbād ibn ʿAbbās.” In , edited by . Syriaca.org, 2016-. Entry published 2020. https://usaybia.net/person/1.
> About this Entry
> Entry Title: ʿAbbād ibn ʿAbbās
> 
> Authorial and Editorial Responsibility:
> Nathan P. Gibson, general editor, Ludwig Maximilian University of Munich (Ludwig-Maximilians-Universität München)
> , editor,
> Vanessa Birkhahn, Fabio Ioppolo, Nadine Löhr, Robin Schmahl, Malinda Tolay, Nathan P. Gibson, Vanessa Birkhahn, Fabio Ioppolo, Nadine Löhr, Robin Schmahl, and Malinda Tolay, entry contributors, “ʿAbbād ibn ʿAbbās”

I'll take it point by point:
> Nathan P. Gibson et al.

- [ ] Please list all `editor[@role="creator"]` (no et al)

> in last modified

We're not using seriesStmt -- irrelevant for this resource. Do we need a `titleStmt/title[@level="m"]` or what for the containing resource?

> last modified 2020 

- [ ] Please include the version number ("version 0.3, last modified 25 June 2020") from `editionStmt/edition/@n`. I see there are two dates in the publicationStmt. Will the full date be displayed once I remove the extra one? 

> In , edited by .

Where can we record the editor of the entire resource if we're not using seriesStmt? 

> Syriaca.org, 2016-. 

Where does this text come from? publicationStmt/authority correctly has Usaybia.net.

> Entry published 2020.

Where does this text come from? 

> , editor,

Why is there an empty editor?

**Comment by wsalesky** [comment]
@nathangibson The empty editors are coming from here: 
https://github.com/usaybia/srophe-eXist-app/blob/master/resources/xsl/citation.xsl#L232

and here: https://github.com/usaybia/srophe-eXist-app/blob/master/resources/xsl/citation.xsl#L100

You do not have any general editors. I can make it conditional, or you can change the rule to match a different role. 

> Where can we record the editor of the entire resource if we're not using seriesStmt?

Perhaps you could use the publication statement? This might be more a question for @davidamichelson. We can code for whatever you decide is best.

**Comment by nathangibson** [comment]
OK, sure, I assume you mean general editors directly under titleStmt? I can add it there.

**Comment by nathangibson** [comment]
Thanks for pointing out the citation.xsl file. Didn't know about that -- will take a look. 
I could see some logic for abstracting the citation a bit more to be useable by other projects, at least where it says "Syriaca.org", which could perhaps come from `publicationStmt/authority`. What do you think?

**Comment by wsalesky** [comment]
@nathangibson Interesting, I believe this is already changed in the Srophe app, just did not make it to Usaybia when I merged in the updates. I will double check though.

**Comment by wsalesky** [comment]
@nathangibson I think this is fixed. Please reopen if you find it is not.

**Comment by nathangibson** [comment]
Still some issues here -- will try to fix

**Comment by wsalesky** [comment]
@nathangibson Do you need me to do anything on this issue?

**Comment by nathangibson** [comment]
I think this is good now, thanks!
