### ISSUE TITLE
Search bar obliterates Place name headword title

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#40]
At first I thought this just had to do with the English headword not displaying for places (#38) but even if I type something into the `h1/span[@id="title"]` manually, it is obliterated by the search bar. I guess the places template must be a bit different from the persons on this.
![Screenshot_2020-07-27 Nahr al-Mahdī](https://user-images.githubusercontent.com/3083452/88524357-81d13800-cff9-11ea-834f-edc5342ef37d.png)

**Comment by nathangibson** [comment]
Also the case for page header on https://dev.usaybia.net/places/browse.html and https://dev.usaybia.net/places/browse.html (but not for persons browse). So I'm guessing this is an issue in the system-wide page template?

**Comment by wsalesky** [comment]
@nathangibson The header for Usaybia is wider then the header for Srophe. I will make the change to the files in the templates folder.

**Comment by wsalesky** [comment]
fixed
