### ISSUE TITLE
Versioning & archival plan

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#43]
@wsalesky As you know I've been trying to tweak our docker deployment. But this is also related to long-term archival. 

What do you think of the following plan? 

 1. Release versions of the data and app as numbered Github releases including the ant-packaged .xar builds, e.g. https://github.com/usaybia/usaybia-data/releases/tag/v0.4-alpha. Question: Should the Usaybia flavor of the Srophe app have its own version numbers? **Edit:** At least by version 1.0 I would aim to have consistency checks that include validation of all TEI.
 1. Fork [Srophe Docker](https://github.com/srophe/srophe-docker) and use it with Github submodules to build Docker images that can be deployed as-is on the server with minimal fuss. (Also a good way to switch to a different server in case of hosting issues.) **Edit:** Pre-built Docker containers could also be done as Github releases.
 1. Add the pre-built Usaybia-Srophe-Docker to Dockerhub? Is this necessary to make docker deployment easy? **Edit:** Also, is there a way to integrate Github with Dockerhub, such that Github-released docker containers can be pushed to Dockerhub?
 1. Github releases from all repos (data, app, docker) will be archived in Zenodo using the Zenodo integration. These automatically get version numbers and DOIs.

**Comment by wsalesky** [comment]
@nathangibson 
1. Sounds good to me and yes I think the Usaybia flavor should have it's own version numbers. 
2.  I need to update the Srophe Docker repository to work with eXist 5+, I will try to get to that today. You can use the Srophe Docker image (to be updated today) as your Docker image, or you can create one specific to Usaybia. 
3. This is not necessary, but you could do it. I do think there is a way to hook up DockerHub and GitHub, it is called continuous integration. I have not yet had time to investigate this option, but we can put it on a wish list. 
4. Sounds good. 
.

**Comment by nathangibson** [comment]
@wsalesky Thanks!

>     2. I need to update the Srophe Docker repository to work with eXist 5+, I will try to get to that today. You can use the Srophe Docker image (to be updated today) as your Docker image, or you can create one specific to Usaybia.

Sure, no rush from my side. My thought is to create one specifically for Usaybia and pull in the app and data packages from those repos. According to https://hub.docker.com/r/existdb/existdb it looks possible to do this in the Dockerfile by linking directly to the xar files on the web rather than using submodules, but we'll see.

>     3. This is not necessary, but you could do it. I do think there is a way to hook up DockerHub and GitHub, it is called continuous integration. I have not yet had time to investigate this option, but we can put it on a wish list.

Did a little more reading and it sounds like automated builds could work well: https://hub.docker.com/r/existdb/existdb.

**Comment by nathangibson** [comment]
Came across this - https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages 

It looks pretty easy to publish docker images to Github using the "package" feature. 

What I might do then is fork the srophe docker repo and use that for configuring stuff, Dockerfile, etc., then build the package but actually push it to the app repo. (That seems to me to be where the pre-built package logically belongs.)

If it's as easy as it sounds, I might just use that route instead of setting up a dockerhub integration.

**Comment by wsalesky** [comment]
@nathangibson The Srophe docker repository has been updated.

**Comment by nathangibson** [comment]
I'm going to archive this overly broad issue and create more specific issues as needed.

>     1. Release versions of the data and app as numbered Github releases including the ant-packaged .xar builds, e.g. https://github.com/usaybia/usaybia-data/releases/tag/v0.4-alpha. 

- [x] Have started doing this

>     2. Fork [Srophe Docker](https://github.com/srophe/srophe-docker) and use it with Github submodules to build Docker images that can be deployed as-is on the server with minimal fuss. (Also a good way to switch to a different server in case of hosting issues.) **Edit:** Pre-built Docker containers could also be done as Github releases.

- [x] Working on building docker images and releasing as Github "packages"

>     3. Add the pre-built Usaybia-Srophe-Docker to Dockerhub? Is this necessary to make docker deployment easy? 

- [x] Unnecessary per 2. above. Docker images can be pulled directly from github packages.
 
>     4. Github releases from all repos (data, app, docker) will be archived in Zenodo using the Zenodo integration. These automatically get version numbers and DOIs.

- [x] Numbered releases (data and app, but not including docker images) are already being archived to Zenodo with DOIs.
