### ISSUE TITLE
Directory URLs add extra stuff before index.html

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#45]
@wsalesky Have I done something wrong in nginx or is this an exist / repo-config setting?

When I try to go to dev.usaybia.net/workshop2020/ or dev.usaybia.net/workshop2020 it redirects me to a 404 on https://dev.usaybia.net/exist/apps/usaybia/workshop2020/%20%20/workshop2020/index.html . Notice the extra workshop2020/%20%20/. But https://dev.usaybia.net/exist/apps/usaybia/workshop2020/index.html and https://dev.usaybia.net/workshop2020/index.html are reachable. 

This is the same on https://dev.usaybia.net/documentation --> https://dev.usaybia.net/exist/apps/usaybia/%20%20/documentation/index.html
However it **doesn't** happen for documentation on the main server https://usaybia.net/documentation

As far as I can tell the nginx settings are the same for both the domain and subdomain. If there are any security issues involved you can email me instead of replying here :-)

**Comment by wsalesky** [comment]
@nathangibson I think it is a problem in the controller.xql. I have no problem accessing this: 
https://dev.usaybia.net/workshop2020/index.html

But do have a problem if I do not add the index.html. I will take a look.

**Comment by wsalesky** [comment]
@nathangibson Actually I think this is the culprit right here: 
https://github.com/usaybia/srophe-eXist-app/blob/master/repo-config.xml#L18

Remove the spaces so the nav-base is an empty element, then you will get the correct path. Although the redirect will only work with the paths built off your nav-base, so they will work for this: 
https://dev.usaybia.net/workshop2020/

but not: 

https://dev.usaybia.net/exist/apps/usaybia/workshop2020/

Do you want me to make the change?

**Comment by nathangibson** [comment]
Yes, this worked beautifully thank you!
