### ISSUE TITLE
Display factoids beside text

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#5]
This will depend on the resolution of https://github.com/usaybia/usaybia-data/issues/4.

I would like to display factoids to the right of the running text, similar to the way you display the linked data bar in the Corpus, but aligned horizontally with the text it pertains to. 

For example (from https://github.com/usaybia/usaybia-data/blob/eff4877dd7cc3b35b8c3f657ed098c55b1632eaf/data/texts/tei/iu-sample-kopf-en-tan.xml#L111):

Column 1 (text):

> He was born in Damascus and brought up there by his father, ʿAlī b. Hamid, a famous oculist, whose other [Kopf, p. 92] son, Hamid b. ʿAlī, took up the same profession.

Column 2 (factoids):

> **Name:** [Hamid b. ʿAlī](https://usaybia.net/person/2) | *[go to factoid >](https://usaybia.net/factoid/1-1)*
>
> **Birth:** [Muhadhdhab al-Dīn ʿAbd al-Raḥīm b. ʿAlī](https://usaybia.net/person/1) was born in [Damascus](https://usaybia.net/place/1). *keyword:* [birth](http://syriaca.org/keyword/birth) | *[go to factoid >](https://usaybia.net/factoid/1-2)*

**Comment by wsalesky** [comment]
@nathangibson What would you think about having the factoids as popups like the footnotes on the Corpus? It might save room. We are going to have image/text/transcript already, and I don't know if you want to include a TOC like the corpus does, but it might be nice. 

Example on the Corpus: https://syriaccorpus.org/345

**Comment by nathangibson** [comment]
I'm open to popups, assuming they're mobile-friendly. I see what you're saying about limited space. We will want a TOC--not sure where the best spot for it is.

**Comment by wsalesky** [comment]
Here is a screen shot of the three column view so far (I don't have the transcription working yet). 
I think the 'extra's' like the TOC and factoids would do better as either popups or columns that slide out, similar to how TEI Publisher does their TOC. 

<img width="1410" alt="Screen Shot 2019-05-07 at 9 28 15 AM" src="https://user-images.githubusercontent.com/1168206/57303057-8040ea80-70aa-11e9-8ff2-8bb0e144da81.png">

**Comment by nathangibson** [comment]
Great!

Will it be possible to select what you want to see in each column? If so, I think we probably only need 2 columns for viewing the text. (Sorry for not making that clearer earlier.) There would be 5 options to select: 
1) Arabic manuscript page images
2) Arabic manuscript text
3) Arabic edition page images
4) Arabic edition text
5) English translation
So far I've only given you examples for 3-5. 

I like the slide-out columns for TOC and factoids. Perhaps the info column on the right side could go on top/bottom or also be a slide-out.

**Comment by wsalesky** [comment]
Yes that is fine. Actually it simplifies things since I couldn't figure out how to page through the image, transcription and translation as they do not have the same page numbers. 

I do think I need some more clarity on the versions. There will be two Arabic versions, each with separate page images? And an English translation? And will the text for all three versions be aligned? Which Arabic version do I have now manuscript or edition? Can I get a TEI Header for all three texts? How will the different versions be distinguished in the TEI header? Also, since you are breaking them up into parts how will the parts be referenced or tied back into the whole?

**Comment by nathangibson** [comment]
As far as TEI headers, I'd just been lazy. I've updated the files with them now.

**Comment by nathangibson** [comment]
Yes, each Arabic version will hopefully have page images. Page and text can be aligned using the facsimile info. What you now have is the Arabic edition. 

The English translation will not have page images. It can be aligned paragraph-by-paragraph with the Arabic, but it is not necessary that users be able to display it side-by-side with any of the page images, only with the two Arabic text versions.

Unfortunately I'm still trying to figure out which manuscript we will use, so I can't give you any info on that, except that it will be structured similarly to the Arabic edition. 

The parts are three levels (which I expect to be nested divs): 
 1. chapters (each will have its own file)
 2. biographical entries 
 3. paragraphs

Gotta run--hope this is enough for now.

**Comment by wsalesky** [comment]
@nathangibson 
Possible factoid display here: http://141.40.254.7:8080/exist/apps/usaybia/texts/iu-sample-mueller-ar-tan?view=translation

Scroll down, when there is a factoid a button will popup on the right side, it should populate only the factoids that are referenced on the screen. We can work on this, or if you have a different method in mind let me know.

**Comment by nathangibson** [comment]
I like this and think it could be a good solution! 

In response to your earlier question, I expect to have multiple factoids per paragraph, at least for the sections we’ve marked up. The system you have here seems like it could be compatible with that. We’ll probably have to try it for a while before I know for sure. It would also be good to try using footnotes (which could then open, highlighted in the sidebar you currently have).

**Comment by nathangibson** [comment]
I guess we would also want a link somewhere beside each factoid to view the factoid detail page. Something like: “see factoid >"

**Comment by nathangibson** [comment]
One other thing: If the factoids reference paragraphs, and the paragraphs are aligned, it shouldn’t matter which document (English or Arabic) the factoids are stored in, right? I would probably want to put them in the Arabic but so far have done the demo in English.

**Comment by wsalesky** [comment]
I will add the link to the factoid detail page. 

It does not matter which document the factoids are in.

**Comment by wsalesky** [comment]
@nathangibson any chance we can get a person record for https://usaybia.net/person/1 to test some factoid functions? (Also we will need to discuss how you want the linked data to work. Are you going to generate and store linked data separately from Syriaca.org, will you want to submit your data to a Syriaca.org triplestore and then query it? ) We should probably have a new issue for linked data.

**Comment by wsalesky** [comment]
@nathangibson Creeping along: You can see the factoid pages from here: http://141.40.254.7:8080/exist/apps/usaybia/text/1?view=translation

There needs to be a discussion about the linked data which is why some of the nice features Dan has on his factoid pages are not working here.

**Comment by nathangibson** [comment]
Actually I think what we had is good for now, so I'm closing this. But we might need some of the discussion here for future reference.
