### ISSUE TITLE
Automatically generate index?

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#51]
@wsalesky I am updating and installing the app package fairly often, but I have to manually run modules/index.xql each time otherwise our search and advanced browse doesn't work. 

Is post-install supposed to take care of this? If so, could you take a look? If not, would it be easy to add that?

**Comment by wsalesky** [comment]
@nathangibson are you reinstalling the app or the data? I wouldn't think you would need to re-index if you are only reinstalling the app, but you would if you are reinstalling the data. To get around it this you can run index.xql once, then download the generated collection.xconf file and save it to the data application before you build and deploy it. 

index.xql, creates an collection.xconf file for the data based on your facet-config.xml files and saves it in '/db/system/config/db/apps/yourdata/collection.xconf'

If you download this generated collection.xconf and save it to your data application before building it, it will deploy with the correct indexes and facets configured.

**Comment by nathangibson** [comment]
@wsalesky Hmm, I've only been reinstalling the app, so not sure why this is happening. Maybe at some point I lost the index and just haven't had it since. We'll see on the next install whether it keeps the index. Otherwise it must be overwriting it somehow. 

I take it this line in pre-install should only affect the srophe-app not the data app: https://github.com/usaybia/srophe-eXist-app/blob/development/pre-install.xql#L32 ? 

By saving it to the data application, do you mean copying it to another location somewhere? I see a collection.xconf in the root of the data repo. Is that where you mean?

**Comment by wsalesky** [comment]
Hum, I think actually you need to comment this out: 
https://github.com/usaybia/srophe-eXist-app/blob/development/post-install.xql#L23

Then you should be fine. I think I was trying to have it run every time you re-install the app, but actually, it would be better to only do the re-index manually as you do not need to reindex the data every time you update the app.

**Comment by nathangibson** [comment]
Thanks! Did that.
