### ISSUE TITLE
Display alternate views/editions

### ISSUE THREAD

**Issue by wsalesky** [usaybia/srophe-eXist-app#7]
@nathangibson 
How will the variouse editions/translations link to each other? tei:relation? Something else? Currently the translation is hardcoded in, but I will need someway to link alternate views/texts.

**Comment by nathangibson** [comment]
Well, there’s the `@corresp` but perhaps you need something that lists all the docs? 

Conceptually I think the best way to model this would be in a work record linking to bibl records, which each then point to the actual files. But if that’s too complicated we could have some more direct pointers.  Here’s a mock example  with an edition, manuscript, and translation (let me know if you want me to create a real record)

```
<bibl xml:id="work-1" type="lawd:ConceptualWork">
            ...
            <idno type="URI">https://usaybia.net/work/1</idno>
            ...
            <bibl xml:id="bib1-1" type="lawd:Edition">
               <title level="m">...</title>
               <ptr target="https://usaybia.net/bibl/1"/>
               <listRelation>
                  <relation active="#bib1-1" ref="dcterms:source" passive="#bib1-2"/>
                  <relation active="#bib1-1" ref="lawd:embodies" passive="https://usaybia.net/work/1"/>
               </listRelation>
            </bibl>
            <bibl xml:id="bib1-2" type="syriaca:Manuscript">
               <title>...</title>
               <listRelation>
                  <relation active="#bib1-2" ref="lawd:embodies" passive="https://usaybia.net/work/1"/>
               </listRelation>
            </bibl>
            <bibl type="syriaca:ModernTranslation" xml:id="bib1-3">
               <lang>en</lang>
               <title>...</title>
               <ptr target="https://usaybia.net/bibl/3"/>
               <listRelation>
                  <relation active="#bib1-3" ref="lawd:embodies" passive="https://usaybia.net/work/1"/>
               </listRelation>
            </bibl>
         </bibl>

```

**Comment by wsalesky** [comment]
@nathangibson This really depends on how you imagine users interacting with the texts and moving from one version to another. If you want to link the Arabic manuscript, Arabic edition, and an English translation all together then I think the bibl example above would be the best way to go. If you only want to access the translations then we can stick with the corresp attribute.  My working model was the first instance where you could access all the different versions/translations from any of the parts, but perhaps you were thinking of a different way to access and interconnect the records? At any rate I think we are getting closer!

**Comment by wsalesky** [comment]
@nathangibson can you add the above example to our sample records so I can test it out?

**Comment by nathangibson** [comment]
This is a stale issue, superceded now by #10
