### ISSUE TITLE
Workflow question

### ISSUE THREAD

**Issue by wsalesky** [usaybia/srophe-eXist-app#78]
@nathangibson Lets establish a workflow for bugs to the master branch that will then need to merged into the development branch. 

My approach would be to make a branch off the master, commit and merge. After a successful merge I would merge the master into the development branch. Does this workflow work for you? (If yes I will merge master into development to pick up the REST API and map change). We could also use cherry-pick, but the first option makes more sense as there should not be anything on master that is not also on development.

**Comment by nathangibson** [comment]
@wsalesky Yes, this sounds sensible, thanks for figuring it out! I've also looked at [git-flow](https://jeffkreeftmeijer.com/git-flow/) -- the philosophy is good but it might overcomplicate things for us. I think what you're suggesting is a good middle way. 

Currently it looks like there will be some file conflicts, probably with Github workflows and issue templates. Let me know if you want me to do any conflict resolution lol.

I think sometime soon we probably want to merge development changes into master -- I've actually been running the dev version on the production site at the moment (yes, laziness) and everything seems to be going okay. Are there any changes to srophe core that still need to be tested in development before we do that?

**Comment by nathangibson** [comment]
By the way just today I started using the Github PR plugin in VS Code (github.vscode-pull-request-github). Very nice.
