### ISSUE TITLE
Searches with diacritics return no results in REST API

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#81]
**Correct:**  
- https://usaybia.net/api/search/persName gives me 2400+ results! 
- https://usaybia.net/api/search/placeName?q=Damascus 
- https://usaybia.net/api/search/persName?q=Muhammad
- https://usaybia.net/api/search/persName?q=%D9%85%D8%AD%D9%85%D8%AF (yay, Arabic!)
- https://usaybia.net/api/search/persName?q=Samarqandi

**No results:** 
- https://usaybia.net/api/search/persName?q=Mu%E1%B8%A5ammad (= Muḥammad, should return a bunch of results such as https://usaybia.net/person/1997)
- https://usaybia.net/api/search/persName?q=%D9%85%D8%AD%D9%85%D9%91%D8%AF (could strip out diacritics to return same as https://usaybia.net/api/search/persName?q=%D9%85%D8%AD%D9%85%D8%AF) 
- https://usaybia.net/api/search/persName?q=Samarqand%C4%AB

**Suggested solution:**
The simplest might be to simply substitute / strip out diacritics and return results for the equivalent expression without diacritics. You're doing something similar already in the eXist search. E.g. ḥ > h, ī > i. Do you need a list? You probably don't yet have the Arabic script ones?

**Comment by wsalesky** [comment]
@nathangibson Thanks! I will research, these should strip diacritics already as it is using the full text search. I suspect it may have something to do with the wildcard I tacked onto the end of the search term. Let me do some testing, but I suspect that is the answer.

**Comment by nathangibson** [comment]
Related #82

**Comment by wsalesky** [comment]
Can be closed when pull request has been reviewed and accepted.

**Comment by nathangibson** [comment]
Thanks!
