### ISSUE TITLE
Searches that include "al-" return no results in REST API 

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-eXist-app#82]
E.g. 
- https://usaybia.net/api/search/persName?q=al-Malik returns 0 but should return same as https://usaybia.net/api/search/persName?q=Malik 
- https://usaybia.net/api/search/persName?q=al-din returns 0 but should return ~ the same as https://usaybia.net/api/search/persName?q=din

"al-" is probably marked as a stopword, but then it should be filtered out rather than dropping the whole expression

**Comment by wsalesky** [comment]
Closing, this is the same issue as #81
